spring:
  application:
    name: "exchange"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8071"
#    import: "configserver:http://localhost:8071"
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/